version: "2"

services:
  gitea_server:
    image: docker.gitea.com/gitea:1.25.1-rootless
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
      - "2222:2222"

  gitea_oidc_server:
    image: node:20-alpine
    restart: always
    volumes:
      - ../:/app
    ports:
      - "3000:3000"
    working_dir: /app
    command: sh -c "npx pnpm run start"